const routeForm = document.getElementById('routeForm');
const fromInput = document.getElementById('fromInput');
const toInput = document.getElementById('toInput');
const langToggle = document.getElementById('langToggle');
const routeBoard = document.getElementById('routeBoard');
const summaryGrid = document.getElementById('summaryGrid');
const cityCards = document.getElementById('cityCards');
const notesList = document.getElementById('notesList');
const citySuggestions = document.getElementById('citySuggestions');
const presetButtons = document.getElementById('presetButtons');
const fromQuickCities = document.getElementById('fromQuickCities');
const toQuickCities = document.getElementById('toQuickCities');

const quickCities = ['Shanghai','Beijing','Tokyo','Seoul','Singapore','Hong Kong','Bangkok','Mumbai','Dubai','Istanbul','London','Paris','Berlin','Amsterdam','Rome','New York','Los Angeles','Toronto','Chicago','Mexico City','São Paulo','Buenos Aires','Santiago','Cairo','Johannesburg','Sydney','Melbourne','Auckland'];
const presets = [['Shanghai','Singapore'],['Tokyo','London'],['Seoul','Los Angeles'],['Paris','New York'],['Dubai','Sydney']];

const copy = {
  en: { eyebrow:'Route-aware travel brief', title:'Sky Route', lead:'Drop in two cities and get a sharp flying brief: weather, time gap, daylight overlap, arrival vibe, and route distance.', from:'From', to:'To', buildBrief:'Build brief', popularRoutes:'Popular routes', citySnapshots:'City snapshots', localConditions:'Local conditions', timingNotes:'Timing notes', travelRead:'Travel read', timezoneGap:'Time gap', routeDistance:'Route distance', daylightOverlap:'Daylight overlap', arrivalVibe:'Arrival vibe', temperature:'Temperature', localTime:'Local time', timezone:'Timezone', daylight:'Daylight', weather:'Weather', tempGap:'Temp gap', contactWindow:'Best contact', routeMood:'Route mood', softRoute:'Easy hop', mediumRoute:'Mid-haul', longRoute:'Long-haul', hours:'hours', km:'km', routeLabel:'Approx route', sameTime:'Same clock band', daylightGood:'Good daylight overlap for coordination.', daylightTight:'Overlap exists but the handoff window is tighter.', daylightHard:'Very limited shared daylight across both cities.', noteTime:'Time rhythm', noteWeather:'Weather contrast', noteWindow:'Best contact window', noteArrival:'Arrival read', departFeel:'Departure', arriveFeel:'Arrival', flightSpan:'Flight span', brightArrival:'Bright arrival', lateArrival:'Late arrival', nightArrival:'Night arrival', workingArrival:'Arrives during a workable local band.', offArrival:'Arrives near off-hours, so handoff may feel slower.', mildWeather:'Weather gap is mild.', roughWeather:'Weather difference is noticeable — pack for contrast.' },
  zh: { eyebrow:'带路线视角的出行简报', title:'Sky Route', lead:'输入两个城市，快速查看这条路线的天气、时差、白天重叠、到达氛围和距离。', from:'出发地', to:'目的地', buildBrief:'生成简报', popularRoutes:'热门路线', citySnapshots:'城市快照', localConditions:'当地情况', timingNotes:'时间提示', travelRead:'路线解读', timezoneGap:'时差', routeDistance:'路线距离', daylightOverlap:'白天重叠', arrivalVibe:'到达氛围', temperature:'温度', localTime:'当地时间', timezone:'时区', daylight:'日照', weather:'天气', tempGap:'温差', contactWindow:'最佳联系时段', routeMood:'路线感受', softRoute:'轻松短途', mediumRoute:'中距离', longRoute:'长途路线', hours:'小时', km:'公里', routeLabel:'预估路线', sameTime:'几乎同一时段', daylightGood:'两地白天重叠较好，沟通会更轻松。', daylightTight:'仍有可用白天重叠，但时间窗更紧。', daylightHard:'两地共享白天时段很少，协调会更难。', noteTime:'时间节奏', noteWeather:'天气对比', noteWindow:'推荐联系时段', noteArrival:'到达判断', departFeel:'出发', arriveFeel:'到达', flightSpan:'路线长度', brightArrival:'明亮抵达', lateArrival:'偏晚抵达', nightArrival:'夜间抵达', workingArrival:'到达时仍在本地比较可工作的时段。', offArrival:'到达时更接近休息时段，衔接可能会慢一些。', mildWeather:'两地天气差异不大。', roughWeather:'两地天气差异明显，注意准备。' }
};
let lang = localStorage.getItem('openkee-lang') || 'en';
function t(key){return copy[lang][key]||key}
function applyLanguage(){document.documentElement.lang=lang;langToggle.textContent=lang==='en'?'中文':'EN';document.querySelectorAll('[data-i18n]').forEach((n)=>n.textContent=t(n.dataset.i18n));renderSuggestions();renderQuickPickers();renderPresets();}
function renderSuggestions(){citySuggestions.innerHTML=quickCities.map((city)=>`<option value="${city}"></option>`).join('')}
function renderQuickPickers(){
  const render=(target,input)=>{target.innerHTML=quickCities.slice(0,12).map((city)=>`<button class="quick-city-btn" type="button" data-city="${city}">${city}</button>`).join('');target.querySelectorAll('[data-city]').forEach((btn)=>btn.addEventListener('click',()=>{input.value=btn.dataset.city;routeForm.requestSubmit();}))};
  render(fromQuickCities,fromInput); render(toQuickCities,toInput);
}
function renderPresets(){presetButtons.innerHTML=presets.map(([a,b])=>`<button class="preset-btn" type="button" data-from="${a}" data-to="${b}">${a} → ${b}</button>`).join('');presetButtons.querySelectorAll('[data-from]').forEach((btn)=>btn.addEventListener('click',()=>{fromInput.value=btn.dataset.from;toInput.value=btn.dataset.to;routeForm.requestSubmit();}))}
async function getJson(url){const res=await fetch(url);if(!res.ok)throw new Error(`${res.status}`);return res.json()}
async function geocode(city){const data=await getJson(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(city)}&count=1&language=en&format=json`);const item=data.results?.[0];if(!item)throw new Error(`No result for ${city}`);return item}
async function weather(lat,lon,timezone){return getJson(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,weather_code,is_day&daily=sunrise,sunset&timezone=${encodeURIComponent(timezone)}&forecast_days=1`)}
function localTime(timezone){return new Intl.DateTimeFormat(lang==='en'?'en-US':'zh-CN',{timeZone:timezone,hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date())}
function localHour(timezone){return Number(new Intl.DateTimeFormat('en-US',{timeZone:timezone,hour:'2-digit',hour12:false}).format(new Date()))}
function timezoneOffsetHours(timezone,date=new Date()){const f=new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false});const p=Object.fromEntries(f.formatToParts(date).filter((x)=>x.type!=='literal').map((x)=>[x.type,x.value]));const u=Date.UTC(+p.year,+p.month-1,+p.day,+p.hour,+p.minute,+p.second);return Math.round((u-date.getTime())/3600000)}
function haversine(lat1,lon1,lat2,lon2){const R=6371,toRad=(v)=>(v*Math.PI)/180,dLat=toRad(lat2-lat1),dLon=toRad(lon2-lon1),a=Math.sin(dLat/2)**2+Math.cos(toRad(lat1))*Math.cos(toRad(lat2))*Math.sin(dLon/2)**2;return Math.round(R*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a)))}
function weatherLabel(code){if([0].includes(code))return lang==='en'?'Clear':'晴';if([1,2,3].includes(code))return lang==='en'?'Cloudy':'多云';if([45,48].includes(code))return lang==='en'?'Fog':'雾';if([51,53,55,61,63,65,80,81,82].includes(code))return lang==='en'?'Rain':'雨';if([71,73,75,77,85,86].includes(code))return lang==='en'?'Snow':'雪';return lang==='en'?'Mixed':'复杂天气'}
function daylightHours(sunrise,sunset){return Math.max(0,Math.round((new Date(sunset)-new Date(sunrise))/36e5))}
function routeMood(distance){return distance<2500?t('softRoute'):distance<7000?t('mediumRoute'):t('longRoute')}
function arrivalVibe(hour){if(hour>=8&&hour<=17)return t('brightArrival');if(hour>17&&hour<=22)return t('lateArrival');return t('nightArrival')}
function bestWindow(fromOffset,toOffset){const gap=Math.abs(fromOffset-toOffset);if(gap<=2)return lang==='en'?'09:00–18:00 in both cities works well.':'两地 09:00–18:00 都比较顺。';if(gap<=6)return lang==='en'?'Aim for late afternoon in one city and morning in the other.':'尽量抓一边下午、另一边上午。';return lang==='en'?'Use the narrow handoff around one side evening and the other side morning.':'尽量抓住一边傍晚、另一边清晨的窄窗口。'}
function render(state){const {from,to,distance,timeGap,daylightOverlap}=state;const arrival=arrivalVibe(to.hour);const tempGap=Math.round(Math.abs(from.temp-to.temp));routeBoard.innerHTML=`<div class="route-spine"><div class="route-node"><p>${t('from')}</p><strong>${from.name}</strong><p>${from.timezone}</p></div><div class="route-center"><p>${t('routeLabel')}</p><strong>${distance.toLocaleString()} ${t('km')}</strong><p>${routeMood(distance)}</p></div><div class="route-node"><p>${t('to')}</p><strong>${to.name}</strong><p>${to.timezone}</p></div></div><div class="arrival-band"><div class="arrival-chip"><p>${t('departFeel')}</p><strong>${from.localTime}</strong><p>${from.weather}</p></div><div class="arrival-chip"><p>${t('flightSpan')}</p><strong>${routeMood(distance)}</strong><p>${t('contactWindow')}: ${bestWindow(from.offset,to.offset)}</p></div><div class="arrival-chip"><p>${t('arriveFeel')}</p><strong>${arrival}</strong><p>${to.localTime}</p></div></div>`;
summaryGrid.innerHTML=[[t('timezoneGap'),`${timeGap} ${t('hours')}`,timeGap===0?t('sameTime'):''],[t('routeDistance'),`${distance.toLocaleString()} ${t('km')}`,''],[t('daylightOverlap'),`${daylightOverlap} ${t('hours')}`,daylightOverlap>=6?t('daylightGood'):daylightOverlap>=3?t('daylightTight'):t('daylightHard')],[t('tempGap'),`${tempGap}°C`,tempGap<=6?t('mildWeather'):t('roughWeather')]].map(([label,value,note])=>`<article class="summary-card"><p>${label}</p><strong>${value}</strong><p>${note}</p></article>`).join('');
cityCards.innerHTML=[from,to].map((city)=>`<article class="city-card"><strong>${city.name}</strong><p>${t('localTime')}: ${city.localTime}</p><p>${t('weather')}: ${city.weather}</p><p>${t('temperature')}: ${Math.round(city.temp)}°C</p><p>${t('daylight')}: ${city.daylight} ${t('hours')}</p><p>${t('timezone')}: ${city.timezone}</p></article>`).join('');
notesList.innerHTML=[[t('noteTime'),timeGap<=2?t('sameTime'):daylightOverlap>=4?t('daylightTight'):t('daylightHard')],[t('noteWeather'),tempGap<=6?t('mildWeather'):t('roughWeather')],[t('noteWindow'),bestWindow(from.offset,to.offset)],[t('noteArrival'),to.hour>=8&&to.hour<=18?t('workingArrival'):t('offArrival')]].map(([title,body])=>`<article class="note-card"><strong>${title}</strong><p>${body}</p></article>`).join('')}
routeForm.addEventListener('submit',async(e)=>{e.preventDefault();try{const [fromPlace,toPlace]=await Promise.all([geocode(fromInput.value.trim()),geocode(toInput.value.trim())]);const [fromWeather,toWeather]=await Promise.all([weather(fromPlace.latitude,fromPlace.longitude,fromPlace.timezone),weather(toPlace.latitude,toPlace.longitude,toPlace.timezone)]);const from={name:fromPlace.name,timezone:fromPlace.timezone,localTime:localTime(fromPlace.timezone),temp:fromWeather.current.temperature_2m,weather:weatherLabel(fromWeather.current.weather_code),daylight:daylightHours(fromWeather.daily.sunrise[0],fromWeather.daily.sunset[0]),offset:timezoneOffsetHours(fromPlace.timezone),hour:localHour(fromPlace.timezone)};const to={name:toPlace.name,timezone:toPlace.timezone,localTime:localTime(toPlace.timezone),temp:toWeather.current.temperature_2m,weather:weatherLabel(toWeather.current.weather_code),daylight:daylightHours(toWeather.daily.sunrise[0],toWeather.daily.sunset[0]),offset:timezoneOffsetHours(toPlace.timezone),hour:localHour(toPlace.timezone)};render({from,to,distance:haversine(fromPlace.latitude,fromPlace.longitude,toPlace.latitude,toPlace.longitude),timeGap:Math.abs(from.offset-to.offset),daylightOverlap:Math.max(0,Math.min(from.daylight,to.daylight))})}catch(error){routeBoard.innerHTML=`<article class="summary-card"><strong>Error</strong><p>${error.message}</p></article>`;summaryGrid.innerHTML='';cityCards.innerHTML='';notesList.innerHTML='';}})
langToggle.addEventListener('click',()=>{lang=lang==='en'?'zh':'en';localStorage.setItem('openkee-lang',lang);applyLanguage();routeForm.requestSubmit();});
applyLanguage();routeForm.requestSubmit();
